[package]
name = "address_lookup_table"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
solana_program ={ package = "otter-solana-program", path = "../program"}
borsh = { workspace = true }
