[package]
name = "onchor_spl"
version = "0.1.0"
edition = "2021"

[dependencies]
kani = { workspace = true, optional = true }
onchor = { path = "../anchor" }

[features]
default = []
kani = ["dep:kani", "onchor/kani"]

[lib]
path = "src/lib.rs"
