[package]
name = "onchor_spl"
version = "0.1.0"
edition = "2021"

[dependencies]
kani = { workspace = true, optional = true }
onchor = { path = "../anchor" }
borsh = { workspace = true }
num_enum = { workspace = true }

[features]
default = []
idl-build = []
dex = []
token = []
kani = ["dep:kani", "onchor/kani"]

[lib]
path = "src/lib.rs"

[lints.rust]
unexpected_cfgs = { level = "allow", check-cfg = ['cfg(kani)'] }
